[package]
name = "dotos-arm"
version = "0.1.0"
authors = ["Łukasz Biel <lukasz.p.biel@gmail.com>"]
edition = "2018"

[dependencies]
cfg-if = "1.0.0"

[features]
board-rpi1 = []
arch-arm = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
