[package]
name = "dotos-arm"
version = "0.1.0"
authors = ["Łukasz Biel <lukasz.p.biel@gmail.com>"]
edition = "2018"

[dependencies]
cfg-if   = "1.0.0"
register = "1.0.2"

[features]
default = ["board-rpi1", "aarch32"]
board-rpi1 = []
aarch32 = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
