[unstable]
build-std = ["core", "compiler_builtins"]

[build]
target = "arm-dotos.json"
rustflags = [
    "-C",
    "link-arg=-Tlinker.ld",
    "-C",
    "link-arg=-ffreestanding",
    "-C",
    "link-arg=-O2",
    "-C",
    "link-arg=-nostdlib",
    "-C",
    "link-arg=-lgcc",
    "-C",
    "link-arg=-otarget/dotos.elf"
]
